import Head from 'next/head'
import Image from 'next/image'
import HomeBanner from '@/components/HomeBanner'
import CategoryBox from '@/components/CategoryBox'
import AccessoriesImg from '@/public/images/accessories.webp'
import LaptopsImg from '@/public/images/Laptops.png'
import PcsImg from '@/public/images/Pcs.png'
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation} from "swiper";
import "swiper/css";

export default function Home() {
  return (
    <>
      <Head>
        <title>SHOPO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className='p-4 sm:p-8'>
        <HomeBanner />

        {/* Categories */}
        <div className='text-center mt-16 md:px-14'>
          <h1 className='text-xl md:text-5xl'>What We Selling?</h1>
         
           <Swiper
             modules={[Navigation]}
             slidesPerView={3}
             className='justify-center mt-12'
             spaceBetween={20}
             draggable={true}
             breakpoints={{
              320:{
                slidesPerView:1.2,
                spaceBetween:5,
               },
            
               820:{
                 slidesPerView:2.2,
                 spaceBetween:5,
               },
                1040:{
                 slidesPerView:3,
                 spaceBetween:5,
                 },
    
           
            }}
           >
            <SwiperSlide>
             <CategoryBox text='Accessories' link='/accessories' img={AccessoriesImg} />
            </SwiperSlide>

            <SwiperSlide>
             <CategoryBox text='Laptops' link='/laptops' img={LaptopsImg} />
            </SwiperSlide>

            <SwiperSlide>
             <CategoryBox text='Pcs' link='/pcs' img={PcsImg} />
            </SwiperSlide>

           </Swiper>
            

       
        </div>
      </main>
    </>
  )
}
