import Head from 'next/head'
import Image from 'next/image'
import HomeBanner from '@/components/HomeBanner'

export default function Home() {
  return (
    <>
      <Head>
        <title>SHOPPO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className='p-4 sm:p-8'>
        <HomeBanner />
      </main>
    </>
  )
}
